### ISSUE TITLE
OsX - atom-1.9.0-beta - Installing “jump-to-import@0.6.0” failed

### ISSUE THREAD

**Issue by me6iaton** [alexheyd/atom-jump-to-import#1]
```
> ctags@3.0.0 install /private/tmp/apm-install-dir-116521-89783-1hyvydf/node_modules/jump-to-import/node_modules/symbols-view/node_modules/ctags
> node-gyp rebuild


make: *** No rule to make target `../../../../../../../../../../Applications/Atom', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/tmp/apm-install-dir-116521-89783-1hyvydf/node_modules/jump-to-import/node_modules/symbols-view/node_modules/ctags
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom Beta.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom Beta.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/imac/.atom/.apm/.apmrc" "--userconfig" "/Users/imac/.atom/.apmrc" "install" "/private/tmp/d-116521-89783-50zdyd/package.tgz" "--target=0.37.8" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/apm-install-dir-116521-89783-1hyvydf/npm-debug.log
```

**Comment by alexheyd** [comment]
Hi, thanks for the log, I was able to reproduce this and it may be an issue with Atom Beta specifically. https://github.com/atom/apm/issues/499

In the meantime, if you install it in regular Atom it's available to use in Atom Beta.
