### ISSUE TITLE
Install failed in Atom 1.17.2

### ISSUE THREAD

**Issue by joshkadis** [alexheyd/atom-jump-to-import#35]
Thanks for your work on this! The Ember stuff specifically will be really useful for me. I got this error when attempting to install v3.6.5 in Atom 1.17.2

```
> ctags@3.0.0 install /private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr/node_modules/jump-to-import/node_modules/ctags
> node-gyp rebuild

  CC(target) Release/obj.target/ctags/src/readtags.o
  CXX(target) Release/obj.target/ctags/src/tags.o
/private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr
`-- (empty)


warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
../src/tags.cc:1:10: fatal error: 'string' file not found
#include <string>
         ^~~~~~~~
1 warning and 1 error generated.
make: *** [Release/obj.target/ctags/src/tags.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr/node_modules/jump-to-import/node_modules/ctags
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr/package.json'
npm WARN apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr No description
npm WARN apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr No repository field.
npm WARN apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr No README data
npm WARN apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr No license field.
npm ERR! Darwin 18.2.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/joshkadis/.atom/.apm/.apmrc" "--userconfig" "/Users/joshkadis/.atom/.apmrc" "install" "/private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/d-1181120-3470-1bb1f28.itow78ehfr/package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! ctags@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ctags@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ctags package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ctags
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ctags
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/sb/tv7z664111qgl4pcpt0dqdn00000gr/T/apm-install-dir-1181120-3470-1ryfiib.gfppq4cxr/npm-debug.log
npm ERR! code 1
```

**Comment by michael-river-island** [comment]
I get a similar error when running `apm install jump-to-import`

I have atom v1.38.2 x64

`apm -v` gives me the following info.

apm  2.1.7
npm  6.2.0
node 8.9.3 x64
atom 1.38.2
python 2.7.10
git 2.21.0

I am running node v11.12.0 and npm v6.7.0 on my machine.
MacOSX Mohave 10.14

**Comment by rodrigoreeis** [comment]
I have same error... 😢 

`> ctags@3.1.0 install /private/var/folders/8n/q_672hh547j2592lv4cs3k9r0000gn/T/apm-install-dir-120414-13993-i93inw.czpfo/node_modules/jump-to-import/node_modules/ctags
`
