### ISSUE TITLE
Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by tadeugr** [alexheyd/atom-jump-to-import#4]
I'm getting this error when I Press CTRL+ALT+E.

Stack trace:
Cannot read property 'find' of undefined
```
TypeError: Cannot read property 'find' of undefined
  at JumpToImport.extractBabelConfig (/home/gcd/.atom/packages/jump-to-import/lib/jump-to-import.js:111:44)
  at /home/gcd/.atom/packages/jump-to-import/lib/jump-to-import.js:99:28
  at Array.forEach (native)
  at JumpToImport.loadBabelConfig (/home/gcd/.atom/packages/jump-to-import/lib/jump-to-import.js:97:22)
  at JumpToImport.packageSetup (/home/gcd/.atom/packages/jump-to-import/lib/jump-to-import.js:65:12)
  at JumpToImport.activate (/home/gcd/.atom/packages/jump-to-import/lib/jump-to-import.js:38:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:184:19)
  at /usr/share/atom/resources/app.asar/src/package.js:827:25
  at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:240:20)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
```

Environment:
- Linux Mint 18 Sarah Cinnamon 64-bit
- Atom 1.12.27

**Comment by alexheyd** [comment]
Thanks for the report, will look into this over the holidays.

**Comment by tadeugr** [comment]
@alexheyd Just a heads up, I realized if if right click on import path and click on "jump-to-import: Go to module" it works.

Also, I forgot to thank you for this package. It helps a lot.

**Comment by alexheyd** [comment]
@tadeugr Should be fixed by https://github.com/alexheyd/atom-jump-to-import/commit/cab1fe76b88a7cab0ff9badf66d2f744d313fdfc

Let me know if you run into any other issues. Thanks!

Also, you're welcome!
