### ISSUE TITLE
Failed to activate the jump-to-import package

### ISSUE THREAD

**Issue by cronco** [alexheyd/atom-jump-to-import#5]
This error shows up when you click the shortcut when cursor not on import statement.

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Mac OS X 10.12.1
**Thrown From**: [jump-to-import](https://github.com/alexheyd/atom-jump-to-import) package, v1.4.0

### Stack Trace

Failed to activate the jump-to-import package

```
At Cannot read property '1' of undefined

TypeError: Cannot read property '1' of undefined
    at JumpToImport.extractBabelConfig (/Users/cronco/.atom/packages/jump-to-import/lib/jump-to-import.js:91:9)
    at /Users/cronco/.atom/packages/jump-to-import/lib/jump-to-import.js:78:27
    at Array.forEach (native)
    at JumpToImport.loadBabelConfig (/Users/cronco/.atom/packages/jump-to-import/lib/jump-to-import.js:76:20)
    at JumpToImport.packageSetup (/Users/cronco/.atom/packages/jump-to-import/lib/jump-to-import.js:51:10)
    at JumpToImport.activate (/Users/cronco/.atom/packages/jump-to-import/lib/jump-to-import.js:27:10)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:827:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:240:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:01.1.0 jump-to-import:go-to-module (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "dev-live-reload",
      "package-cop",
      "switcheroo",
      "git-time-machine",
      "language-vue"
    ],
    "ignoredNames": [
      "dist/* clean/* tags"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-prettify, v0.1.3 (inactive)
atomic-chrome, v0.3.0 (active)
batman-syntax, v1.0.1 (inactive)
chester-atom-syntax, v0.1.1 (inactive)
color-picker, v2.2.3 (active)
django-templates, v0.5.0 (active)
emmet, v2.4.3 (active)
ex-mode, v0.13.1 (inactive)
git-log, v0.4.1 (active)
git-plus, v6.0.1 (active)
git-time-machine, v1.5.4 (inactive)
jump-to-import, v1.4.0 (inactive)
language-vue, v0.21.0 (inactive)
linter, v1.11.18 (active)
linter-eslint, v8.0.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.7 (active)
minimap-autohide, v0.10.1 (active)
multirow-tabs, v0.3.3 (inactive)
package-cop, v0.2.10 (inactive)
pretty-json, v1.6.1 (active)
react, v0.16.1 (active)
react-es6-snippets, v0.3.0 (active)
relative-numbers, v0.6.0 (active)
Remote-FTP, v0.9.4 (active)
set-syntax, v0.3.2 (active)
spacegray-eighties-ui, v1.2.0 (inactive)
ssh-config, v0.10.1 (active)
svgo, v2.6.0 (inactive)
switcheroo, v1.1.0 (inactive)
symbol-gen, v1.3.1 (active)
vim-mode, v0.65.2 (active)
vim-mode-plus-project-find-from-search, v0.1.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by alexheyd** [comment]
@cronco Should be fixed by https://github.com/alexheyd/atom-jump-to-import/commit/cab1fe76b88a7cab0ff9badf66d2f744d313fdfc

Let me know if you run into any other issues. Thanks!
