### ISSUE TITLE
Error while trying to jump to require

### ISSUE THREAD

**Issue by dmytro-lymarenko** [alexheyd/atom-jump-to-import#9]
Tried to open this: const devConfig = require('../../webpack/dev.config');

Version of atom: 1.13.1
Version of atom-jump-to-import: 2.1.1

Error:

`Uncaught TypeError: Cannot read property 'forEach' of null
/home/dmytro/.atom/packages/jump-to-import/lib/atom-utils.js:118
Hide Stack Trace
TypeError: Cannot read property 'forEach' of null
    at Object.extractImportPath (/home/dmytro/.atom/packages/jump-to-import/lib/atom-utils.js:118:12)
    at JumpToImport.getPathFromVariable (/home/dmytro/.atom/packages/jump-to-import/lib/jump-to-import.js:177:28)
    at JumpToImport.getModule (/home/dmytro/.atom/packages/jump-to-import/lib/jump-to-import.js:253:28)
    at JumpToImport.openModule (/home/dmytro/.atom/packages/jump-to-import/lib/jump-to-import.js:192:25)
    at JumpToImport.goToModule (/home/dmytro/.atom/packages/jump-to-import/lib/jump-to-import.js:188:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:259:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:587:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:382:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:106:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:59)
The error was thrown from the jump-to-import package. Atom is out of date: 1.13.1 installed; 1.14.3 latest. Upgrading to the latest version may fix this issue.`

**Comment by alexheyd** [comment]
Also not currently supported :) it's only looking for `import` statements. Could add this at a later point.

**Comment by alexheyd** [comment]
Support for `require` now included.
